# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 04fe47605f67cbb45bb6211661b980f5d58658f3647677917cfc6112e2c72332c15367eff6cef4880f699547447cd06da43b0adacb37c576360d2622e734063f

test:
  secret_key_base: 6bdee7a94455ce3657a28611add9529b5ebcd41076deabc68d8c9ddad0f8f7a371fcaa1a547bf78297e5a0bd3c7dac4754d9445062274b0cebc74394da5e1515

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
