users:
  name:
    max_length: 50
  email:
    max_length: 255
  password:
    min_length: 6
  users_helper:
    size_gravatar: 80
  password_reset_expired: 2
user:
  user_per_page: 5
sessions:
  create:
    remember: "1"
seed:
  total_users: 99
